### ISSUE TITLE
singleflight: hidden bug ?

### ISSUE THREAD

**Issue by junli1026** [golang/groupcache#101]
I commented in the code, the c.wg could be nil this that case. 

```
func (g *Group) Do(key string, fn func() (interface{}, error)) (interface{}, error) {
	g.mu.Lock()
	if g.m == nil {
		g.m = make(map[string]*call)
	}
	if c, ok := g.m[key]; ok {
		g.mu.Unlock()
                // At this time, if another running procedure called delete(g.m, key). 
               // The corresponding 'c' will be deleted; although the current c is a copy, 
               // the waitGroup is the same one shared by them, so it could happens that c.wg is nil. 
		c.wg.Wait()  
		return c.val, c.err
	}
	c := new(call)
	c.wg.Add(1)
	g.m[key] = c
	g.mu.Unlock()

	c.val, c.err = fn()
	c.wg.Done()

	g.mu.Lock()
	delete(g.m, key)
	g.mu.Unlock()

	return c.val, c.err
}
```

**Comment by junli1026** [comment]
Just realized that the m is type "map[string]*call" ,  thus it could happen that:
                                       TIMELINE
                                            |
goroutinue 1 :                     |                      go routinue 2: 
                                            |
     ...                                    |
      ...                                   |                      if c, ok := g.m[key]; ok {
      ...	                           |                                    g.mu.Unlock()
	                                   |                      
    g.mu.Lock()                     |
    delete(g.m, key)              |
    g.mu.Unlock()                 |
      ....                                  |                                       c.wg.Wait()    //c has been deleted by goroutinue 1.
      ...	                           |                                       return c.val, c.err
      ...                                  |                        }
      .....                              \ |/

**Comment by bradfitz** [comment]
c.wg can never be nil, because it's not a pointer. It's a `sync.WaitGroup`. And the map contains a pointer to the call. If something deletes it from the map, that doesn't clear its contents, either.

I don't see a bug here.
