### ISSUE TITLE
About package singleflight, I feel something strange 

### ISSUE THREAD

**Issue by skyqinsc** [golang/groupcache#106]
```
func (g *Group) Do(key string, fn func() (interface{}, error)) (interface{}, error) {
	g.mu.Lock()
	if g.m == nil {
		g.m = make(map[string]*call)
	}
	if c, ok := g.m[key]; ok {
		g.mu.Unlock()
		c.wg.Wait()
		return c.val, c.err
	}
	c := new(call)
	c.wg.Add(1)
	g.m[key] = c
	g.mu.Unlock()

	c.val, c.err = fn()
	c.wg.Done()

	g.mu.Lock()
	delete(g.m, key)
	g.mu.Unlock()

	return c.val, c.err
}
```

Above function, I think it may be too complex. It's similar to broking goroutine with mutex, so `sync.WaitGroup` is necessary.

**Comment by bradfitz** [comment]
If you want to rewrite it to be more readable and more performant, feel free. I don't follow what you're proposing, though. You can send a PR if you find something better. Be sure to include CPU & alloc benchmarks.
