### ISSUE TITLE
Is there a plan to add support for Go modules?

### ISSUE THREAD

**Issue by easwars** [golang/groupcache#133]
This is a request from the gRPC-Go team.
We plan to use the LRU cache implementation found here and would be nice if `groupcache` had Go modules support.

I can send a PR for the same if you are OK.

**Comment by bradfitz** [comment]
You mean just adding a `go.mod` file? It should work without one, but sure. Feel free to send a PR.

How is gRPC-Go using groupcache?

**Comment by easwars** [comment]
We are only interested in using the LRU implementation from groupcache. We plan to use that in one of the loadBalancing policy implementations where we need to cache the responses from a management server.

On second thoughts, maybe we should just duplicate that code.

**Comment by bradfitz** [comment]
Yeah, I'd just duplicate it. There are many LRU implementations around with various properties too.

**Comment by easwars** [comment]
Thanks.
