### ISSUE TITLE
concurrent jobs doing GetGroup and NewGroup

### ISSUE THREAD

**Issue by liuplgtm** [golang/groupcache#146]
if multiple jobs use GetGroup to check a group is not present, they will all go to do NewGroup, which will panic:
https://github.com/mailgun/groupcache/blob/master/groupcache.go#L111

Any advice on how to coordinate the different jobs? Thanks,

**Comment by liuplgtm** [comment]
@bradfitz could you help on this, thanks

**Comment by thrawn01** [comment]
You need to preform the init in a thread safe manner or preform a `sync.Once`. I've had a similar discussion here in regards to groupcache init. https://github.com/mailgun/groupcache/pull/23#issuecomment-730797105

**Comment by liuplgtm** [comment]
thanks,
