### ISSUE TITLE
Huh, interesting rabbit hole here. One thing I noticed is that `CreateProcess` itself will handle path resolution if you pass it a non-absolute executable name as argv[0] and NULL as the actual executable path name:

### ISSUE THREAD

**Issue by fahad2022anan** [golang/groupcache#160]
Huh, interesting rabbit hole here. One thing I noticed is that `CreateProcess` itself will handle path resolution if you pass it a non-absolute executable name as argv[0] and NULL as the actual executable path name:

![image](https://user-images.githubusercontent.com/10643/108271223-c0366c00-7170-11eb-88b7-7d0d1f6ec534.png)
from https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa

As an aside from the specific proposal here, this makes me wonder if instead of having exec.Command use LookPath, it should instead use that behavior of CreateProcess, and then we always do what windows does.

---

With regards to NeedCurrentDirectoryForExePath, here's what kernelbase.dll is doing on Windows 10, translated from the x86 into Go:

```go
if strings.Index(exePath, `\`) != -1 { return true }
_, ok := os.Environ()["NoDefaultCurrentDirectoryInExePath"]
return !ok
```

So when you write:

> Note that this proposal is different from just looking at the existence of a NoDefaultCurrentDirectoryInExePath environment variable because the function doesn't just look in the process environment variables but might also look in registry settings.

I'm not sure that this is actually true. Are there other versions of Windows you think I should look at?

_Originally posted by @zx2c4 in https://github.com/golang/go/issues/43947#issuecomment-780877042_

**Comment by bcmills** [comment]
The `golang/groupcache` issue tracker is not the right place to have this discussion.

**Comment by bcmills** [comment]
(Also, when you are quoting text from a reference, please paste text, not screenshots. Screenshots are much less accessible, and also difficult to quote in replies.)
