### ISSUE TITLE
A bug in getting from peers

### ISSUE THREAD

**Issue by lazywei** [golang/groupcache#18]
Reproduce steps
```go
pool := groupcache.NewHTTPPool("http://127.0.0.1:"+os.Getenv("PORT"))
cache := groupcache.NewGroup("cacher", 64<<20, someGetterFunc)
pool.Set("http://127.0.0.1:50000", "http://127.0.0.1:50001")
```
and run it in two port `:50000` and `:50001`
Now, if use `/xxx` as a key, then the groupcacher will act like there is no any peer.
i.e. It will only get data from locally, instead of getting from peers.

The problem is the **slash** in the head of the key (i.e. if the key is `xxx` then everything goes right), and I still can't figure out why.

**Comment by codeskyblue** [comment]
This is 2015 and this bug is 2013, very funny. I began to use this in my `minicdn` project recently and meet this problem, too. I almost reviewed the whole code. The fix is very simple and I already send a pull request, waiting for merge.

**Comment by bradfitz** [comment]
Sounds like this was fixed already but this bug wasn't closed.
