### ISSUE TITLE
Need a function clear all caches

### ISSUE THREAD

**Issue by dingoxiong** [golang/groupcache#43]
I have many html files,  want to be cached in groupcache.  
But, these files will be changed sometimes , not  frequently.
If i watching the folder, when a file be changed, i will get a notice.
Then clear all the caches in gourpcache, and do not need to restart my service.

**Comment by adg** [comment]
Put a serial number in your cache key and increment the number when you want to reload the files. Groupcache keys should uniquely identify content that never changes.
