### ISSUE TITLE
Replicas being consistently set to 50

### ISSUE THREAD

**Issue by artushin** [golang/groupcache#49]
It looks like https://github.com/golang/groupcache/blob/master/http.go#L123 is consistently setting the number of replicas to 50 as soon as peers.Set is called, disabling the ability to set the Replicas option.

**Comment by dvirsky** [comment]
Yep. The question is whether how we store the configured number. another member to the pool itself? maybe save the entire pool opts objects in it?

**Comment by artushin** [comment]
I think just a pointer to opts used after creating the the pool is fine - see the PR

**Comment by dvirsky** [comment]
Seems cool to me

**Comment by pierrre** [comment]
Fixed by #63 , we can close this issue.
