### ISSUE TITLE
What is the lru list in cache for?

### ISSUE THREAD

**Issue by RealHacker** [golang/groupcache#51]
The lru list is maintained, but I don't see it used anywhere.
This is not a bug, but I don't know where to post questions/comments.

**Comment by adg** [comment]
It's used in the `cache` type's `add` and `get` methods.

**Comment by adg** [comment]
You can post questions on the golang-nuts mailing list.

**Comment by RealHacker** [comment]
Thanks! 
The order of list ll is maintained in add and get, but I don't see ll used anywhere.

**Comment by adg** [comment]
Check out the `removeOldest` method.
