### ISSUE TITLE
A bug in sink.go

### ISSUE THREAD

**Issue by tw4452852** [golang/groupcache#6]
```go
func (s *stringSink) SetProto(m proto.Message) error {
	b, err := proto.Marshal(m)
	if err != nil {
		return err
	}
        // Should clear the old string
        s.v.s = ""
	s.v.b = b
	*s.sp = string(b)
	return nil
}
```
As the comment says, if I call `*stringSink.SetString` first and then call `*stringSink.SetProto`, the `stringSink.v` will be messed up.

**Comment by bradfitz** [comment]
Seems like this is harmless if people follow the rules, and it's obviously not been biting people for the past 3 years (not enough for anybody to send a fix, so I'm going to close this.
