### ISSUE TITLE
Go 1.7 context support

### ISSUE THREAD

**Issue by pierrre** [golang/groupcache#68]
Hello !
Is there a plan for Go 1.7 context support?

**Comment by bradfitz** [comment]
There is no current plan.

**Comment by pierrre** [comment]
OK thank you.
I'll do it myself.

**Comment by bradfitz** [comment]
That's not to say it can't happen in this repo. But Go 1.7 isn't even out yet, so it seems premature to add here as a requirement.

We can use golang.org/x/net/context in the meantime and keep compatibility back a few versions.
