### ISSUE TITLE
Currently found in the use of HttpPool groupcache, key to "/" at the beginning of the peer can not exchange data between bug hope to solve the next?

### ISSUE THREAD

**Issue by shotdog** [golang/groupcache#72]
Currently found in the use of HttpPool groupcache, key to "/" at the beginning of the peer can not exchange data between bug hope to solve the next?
 thinks

**Comment by bradfitz** [comment]
I don't totally understand.

Do you have an example?

**Comment by shotdog** [comment]
`golang`
package main

import (
	"net/http"

	"github.com/golang/groupcache"
	"os"
	"log"
)

func main() {

	me := os.Args[1]
	pool := groupcache.NewHTTPPool("http://127.0.0.1:" + me)
	pool.Set("http://127.0.0.1:8081", "http://127.0.0.1:8082")

	group := groupcache.NewGroup("group1", 1 << 32, groupcache.GetterFunc(func(context groupcache.Context, key string, dest groupcache.Sink) error {
		log.Println("key=", key)

		dest.SetBytes([]byte(me));
		return nil
	}))

	http.HandleFunc("/", func(response http.ResponseWriter, request *http.Request) {

		path := request.URL.Path
		log.Println("path=", path)

		var data []byte

		group.Get(nil, path, groupcache.AllocatingByteSliceSink(&data))

		response.Write(data)

	})

	http.ListenAndServe("127.0.0.1:" + me, nil)

}

func peers(hosts []string) []string {

	peers := make([]string, len(hosts))

	for i, v := range hosts {

		peers[i] = "http://127.0.0.1:" + v
	}
	return peers
}




go build main.go 

./main 8081 
./main 8082


open the broswer  
like this 
http://127.0.0.1:8081/1
http://127.0.0.1:8081/2

but i can not get the cache data from 8082 peer

**Comment by codeskyblue** [comment]
you can see my folk. fixed this bug

**Comment by shotdog** [comment]
@codeskyblue  good! why do you not pull a request   ?

**Comment by codeskyblue** [comment]
actually I have made pr before.

**Comment by ww156** [comment]
@shotdog I think it‘s ok,you just request five,if you request 500,you should get the data from 8082 peer.

**Comment by bradfitz** [comment]
Sounds like it's just unfortunate hashing for keys 1-5, if I read @ww156's comment correctly.
