### ISSUE TITLE
many function should check parameter

### ISSUE THREAD

**Issue by knightXun** [golang/groupcache#82]
i find lru/cache.go does't check parameter.if user use negative number,it may be unusable.

**Comment by knightXun** [comment]
if let me rewirte the code,it would be hounorable to me.

**Comment by bradfitz** [comment]
I don't think this is a common enough problem to worry about.

If users want to shoot themselves in the foot, feel free. In fact, this package isn't supposed to be public. It's an internal detail but predates Go's internal package mechanism.
