### ISSUE TITLE
sir there is no delete func in consistenthash

### ISSUE THREAD

**Issue by huangsanye** [golang/groupcache#86]
sir there is no delete func in consistenthash

**Comment by bradfitz** [comment]
Yes, https://godoc.org/github.com/golang/groupcache/consistenthash only supports what was needed by groupcache itself. It was not intended to be a public package, but Go's "internal" package mechanism didn't exist at the time I wrote groupcache.

I suppose I could move it to be an internal package, but that wouldn't necessarily solve your problem.

You might want to fork the package, or use a different consistent hash package.
