### ISSUE TITLE
support expire ttl ?

### ISSUE THREAD

**Issue by rfyiamcool** [golang/groupcache#92]
see title, thanks u.

**Comment by bradfitz** [comment]
It was an explicit decision to not support expiration TTLs, as that would encourage people to use it wrong and add versioned values. If you need a TTL, include the validity period into the key itself. For example, if the key is only good for 5 minutes, round down to the current time / 5 minutes, and put that in the key.

But for a given key, there should only be one value ever.

Unaccessed keys fall off the end of the LRU.
