### ISSUE TITLE
Support for destruction of group

### ISSUE THREAD

**Issue by Jamesxql** [golang/groupcache#93]
Currently only supports creating a new group and getting an existing group, is it possible to provide a way to destroy an existing group?

**Comment by bradfitz** [comment]
No, it is not currently possible.

By destroy do you mean immediately free memory, or close network connections to peers?

Typically programs have a fixed number of groups (usually 1) for the lifetime of their program.

What is your use case?

**Comment by Jamesxql** [comment]
In my program, I do not need to use groupcache as a distributed cache service, I just use groupcache as a cache library. 

So I wish I can control the lifetime of the group, at the appropriate time, I hope to immediately free memory which used by the group. 

Therefore, I hope groupcache package can provide a way to destroy the group which I previously created.

**Comment by bradfitz** [comment]
In that case, just lose a reference to it and it'll all be garbage collected. You don't need to shut it down or anything.

**Comment by Jamesxql** [comment]
In my case,  I have some data that needs to be cached and the data will not change for a long time. When the cached data changes, I will be notified. 

So, when notified, I want to destroy the previously created group object, freeing up the memory it occupies, and create a new group object to hold the new data.

I don't want to use memcached or redis to do this. If you have a better idea, you can tell me too. 

Thanks very much @bradfitz

**Comment by Jamesxql** [comment]
However, the created group object is saved in the global variable named `groups`, GC will free the memory it occupies even if not `delete(groups, name)`? Why?

**Comment by bradfitz** [comment]
Oh, true.
 
I really don't want to add new API to this, though. If you just want an LRU cache, there are a hundred on github / godoc.org. What makes groupcache interesting enough to use it by itself without peer nodes?

**Comment by Jamesxql** [comment]
Mainly for this reason: 

> comes with a cache filling mechanism. Whereas memcached just says "Sorry, cache miss", often resulting in a thundering herd of database (or whatever) loads from an unbounded number of clients (which has resulted in several fun outages), groupcache coordinates cache fills such that only one load in one process of an entire replicated set of processes populates the cache, then multiplexes the loaded value to all callers.

It's brilliant.

**Comment by bradfitz** [comment]
Well, if you want that part, there is:

https://godoc.org/github.com/golang/groupcache/singleflight

Combine that with an LRU, and that's all you need?

**Comment by Jamesxql** [comment]
OK, I will customize a cache library, reference groupcache implementation, thanks a lot. @bradfitz
