### ISSUE TITLE
Is there a need to add a mutex for concurrent Add the lru cache?

### ISSUE THREAD

**Issue by HongyanShen** [golang/groupcache#94]
Is it ok for [this function](https://github.com/golang/groupcache/blob/master/lru/lru.go#L56)  without a mutex if there is more than one goroutines to Add cache?

**Comment by bradfitz** [comment]
The docs on the type say:

https://godoc.org/github.com/golang/groupcache/lru#Cache

> // Cache is an LRU cache. It is not safe for concurrent access.

**Comment by HongyanShen** [comment]
@bradfitz thks
